on:
  push:
    branches:
      - next

name: Deploy to Aruba on push

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js 20
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Build
        run: npm run build
      
      - name: Upload to Aruba
        uses: aruba/upload-to-aruba@v1.1.0
        with:
          host: ftp.baialupo.com
          username: 733495@aruba.it 
          password: admin
          path: /www.baialupo.com/new