name: Deploy to GitHub Pages

on:
  push:
    branches: [main]
  # Allows you to run this workflow manually from the Actions tab on GitHub.
  workflow_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
  pages: write
  contents: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout your repository using git
        uses: actions/checkout@v4
        with:
            fetch-depth: 0

      - name: Generate a changelog
        uses: orhun/git-cliff-action@v4
        id: git-cliff
        with:
          config: cliff.toml
          args: --verbose
        env:
          OUTPUT: CHANGELOG.md
          GITHUB_REPO: ${{ github.repository }}

      - name: Commit
        run: |
          git checkout main
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          set +e
          git add CHANGELOG.md
          git commit -m "chore: update changelog"
          git pull --rebase
          git push https://x-access-token:${{ secrets.GIT_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Install and build astro website
        uses: withastro/action@v2
        with:
            # The Node package manager that should be used to install dependencies and build your site. Automatically detected based on your lockfile. (optional)
            package-manager: pnpm@latest 
            # The root location of your Astro project inside the repository. (optional)
            # path: . 
            # The specific version of Node that should be used to build your site. Defaults to 18. (optional)
            # Dec, 5th - Ubuntu-latest workflows will use Ubuntu-24.04 image - https://github.com/actions/runner-images/issues/10636
            # node-version: 20 

      - name: Upload files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp.baialupo.com
          local-dir: ./dist/
          server-dir: /www.baialupo.com/web/
          username: ${{ secrets.ARUBA_FTP_USER }}
          password: ${{ secrets.ARUBA_FTP_PWD }}