name: Deploy to Aruba on push

on:
  push:
    branches:
      - next
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get ip
        run: curl -s https://api.ipify.org

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Checkout
        uses: actions/checkout@v3
      
      - name: Build
        run: |
          echo "Free space:"
          df -h
          
      - name: Build
        uses: withastro/action@v2
        with: 
          package-manager: pnpm@latest

      - name: Upload to Aruba
        uses: SamKirkland/FTP-Deploy-Action@v4.3.5
        with:
          server: ftp://ftp.baialupo.com
          username: ${{ secrets.ARUBA_FTP_USER }} 
          password: ${{ secrets.ARUBA_FTP_PWD }}
          local-dir: ./dist
          server-dir: /www.baialupo.com/new2
